### PR TITLE
fix(checkbox): fix settings option when handling booleans

### LINKED ISSUE #354: Attempting to create a boolean setting but wont save when toggled off
@brunomota im attempting to create a setting with type boolean. but its not saving when its toggled off. Any ideas why? 

link to code: https://github.com/lwhiteley/relax/blob/maintennance/lib/shared/screens/admin/screens/settings/screens/maintenance/index.js#L8

fyi im getting this warning: 
warning

### PR DESCRIPTION
**Pull request by lwhiteley**
Issue as outlined prevents a checkbox input type from saving a false value to the database.
This fix allows false values to be considered for storing.

The fix required the checkbox values to actually be booleans to work properly when handled by the reducer. Therefore, the option's value is/should be forced to type boolean when being set

Changelog:
- fix action when saving boolean settings
- handle checkbox warning when setting boolean value

resolves #354

### CODE REVIEW

File: lib/shared/screens/admin/shared/components/options-list/option.jsx [hunk 1]
```diff
@@ -101,15 +102,18 @@ export default class Option extends Component {
       OptionsList,
       value,
       white,
+      type,
```
Comment (bruno12mota) [inline lib/shared/screens/admin/shared/components/options-list/option.jsx]: where does this come from?

File: lib/shared/screens/admin/shared/components/options-list/option.jsx [hunk 2]
```diff
@@ -101,15 +102,18 @@ export default class Option extends Component {
...
       elementOverride,
       displayOverride
     } = this.props;
 
+    const optionValue = (type && type.toLowerCase() === 'boolean')? boolean(value):value;
```
Comment (bruno12mota) [inline lib/shared/screens/admin/shared/components/options-list/option.jsx]: I think we can do this by simply converting if it's not a boolean:

```js
const optionValue = typeof value === 'boolean' ? value : boolean(value);
```

Comment (lwhiteley) [inline lib/shared/screens/admin/shared/components/options-list/option.jsx]: the value that is brought forward is a string, thats why i needed to check if the input type was intended to be a boolean. it comes from the input type

Comment (bruno12mota) [inline lib/shared/screens/admin/shared/components/options-list/option.jsx]: I got that, the verification was odd though 😛

File: lib/shared/screens/admin/shared/components/options-list/option.jsx (hunk 1 above)
Comment (lwhiteley) [inline lib/shared/screens/admin/shared/components/options-list/option.jsx]: do we still need to take this out or are the adjustments ok?

Comment (bruno12mota) [inline lib/shared/screens/admin/shared/components/options-list/option.jsx]: The string to boolean logic should be inside the Checkbox component. And you can verify if the value is a string and convert to boolean in case it is a string.

Comment (lwhiteley) [inline lib/shared/screens/admin/shared/components/options-list/option.jsx]: yea i did that before but the warning that value was passed as a string instead of a boolean came up. 

should i change the proptype to string and then cast to boolean?

Comment (bruno12mota) [inline lib/shared/screens/admin/shared/components/options-list/option.jsx]: You can use the oneOfType:

```js
value: PropTypes.oneOfType([
    PropTypes.string,
    PropTypes.bool
])
```

Comment (lwhiteley) [inline lib/shared/screens/admin/shared/components/options-list/option.jsx]: ah makes total sense lol, give me a sec

**Comment by lwhiteley** [comment]
cool updated and tested, let me know if you need anything updated

**Comment by bruno12mota** [comment]
Awesome 👍

**Comment by bruno12mota** [comment]
Just for reference, we're using yarn. So for future reference you should have also run:

```bash
yarn add boolean
```

This would add the boolean dependency to yarn lock file. I'll add it now no worries 🙂

**Comment by lwhiteley** [comment]
cool man, thanks for the heads up
